"""
DO NOT EDIT.
This stub file was autogenerated.
Do not edit by hand.
"""

from __future__ import annotations
from typing import overload, Literal, Any
try:
    import carla
except Exception:
    carla = None  # type: ignore

class SensorOtherCollisionStub:
    def __init__(self, sensor_bp: 'carla.ActorBlueprint | None' = None) -> None:
        self.sensor_bp = sensor_bp

    @overload
    def set_attribute(self, name: Literal['role_name'], value: Literal['front', 'back', 'left', 'right', 'front_left', 'front_right', 'back_left', 'back_right']) -> None: ...
    def set_attribute(self, name: str, value: Any) -> None:
        if self.sensor_bp is None:
            return
        # CARLA expects string values for blueprint attributes
        self.sensor_bp.set_attribute(name, str(value))

    def setAttribute(self, name: str, value: Any) -> None:
        self.set_attribute(name, value)

__all__ = [
    'SensorOtherCollisionStub',
]
